"""Embeds the web UI (web/html, web/css, web/js) into the firmware image.

Each asset is gzip-compressed and emitted as a C array into a generated
header in the build directory, which is added to the include path. The
web server serves these arrays with `Content-Encoding: gzip`.

JS files are concatenated in sorted filename order into a single app.js.
"""
import gzip
import os

Import("env")  # noqa: F821

PROJECT_DIR = env["PROJECT_DIR"]
BUILD_DIR = env.subst("$BUILD_DIR")
WEB_DIR = os.path.join(PROJECT_DIR, "web")
OUT_DIR = os.path.join(BUILD_DIR, "generated")
OUT_FILE = os.path.join(OUT_DIR, "web_assets.h")


def _read(path):
    with open(path, "rb") as f:
        return f.read()


def _collect():
    assets = {}
    html = os.path.join(WEB_DIR, "html", "index.html")
    css = os.path.join(WEB_DIR, "css", "app.css")
    assets["WEB_INDEX_HTML"] = _read(html)
    assets["WEB_APP_CSS"] = _read(css)
    js_dir = os.path.join(WEB_DIR, "js")
    js = b""
    for name in sorted(os.listdir(js_dir)):
        if name.endswith(".js"):
            js += _read(os.path.join(js_dir, name)) + b"\n"
    assets["WEB_APP_JS"] = js
    return assets


def _emit(assets):
    os.makedirs(OUT_DIR, exist_ok=True)
    lines = [
        "// Auto-generated by tools/embed_web.py - do not edit.",
        "#pragma once",
        "#include <cstdint>",
        "#include <cstddef>",
        "",
    ]
    for name, data in assets.items():
        gz = gzip.compress(data, 9)
        lines.append(f"// {name}: {len(data)} bytes raw, {len(gz)} bytes gzipped")
        body = ",".join(str(b) for b in gz)
        lines.append(f"static const uint8_t {name}_GZ[] = {{{body}}};")
        lines.append(f"static const size_t {name}_GZ_LEN = {len(gz)};")
        lines.append("")
    with open(OUT_FILE, "w") as f:
        f.write("\n".join(lines))
    print(f"Embedded web assets -> {OUT_FILE}")


_emit(_collect())
env.Prepend(CPPPATH=[OUT_DIR])
